name: Run tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torchvision==0.7.0
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest